spring:
  main:
    allow-circular-references: true
  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false
  fhir:
    auth:
      ignored-paths: "metadata,fhir/metadata"
hapi:
  fhir:
    cors:
      allowed_origin:
        - "*"
    fhir_version: R4
    implementationguides:
      us-core:
        name: hl7.fhir.us.core
        version: 8.0.0
        package_url: file:/app/package/us-core-8.0.0.tgz
        install_mode: STORE_AND_INSTALL
    validation:
      requests_enabled: true
      response_enabled: true
      # Allow fetching of unknown profiles
      fetch_remote_resources: true
      allow_external_references: true
      # Set validation policy to be less restrictive
      validation_policy: FETCH_REMOTE_RESOURCES
    terminology:
      enabled: true
      # Allow external code system lookups
      enable_external_lookups: true