services:
  fhir-db:
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${FHIR_DB_USERNAME}
      POSTGRES_PASSWORD: ${FHIR_DB_PASSWORD}
    command: postgres -c max_connections=220
    volumes:
      - "./volumes/fhir-db-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${FHIR_DB_USERNAME} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  id-db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${ID_DB_USERNAME}
      POSTGRES_PASSWORD: ${ID_DB_PASSWORD}
    volumes:
      - "./volumes/id-db-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ID_DB_USERNAME} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  fhir-db-data:
  id-db-data:
